### PR TITLE
Make site logo configurable

### PR DESCRIPTION
**Pull request by metbril**
Make site logo configurable, just like in the h-card.

### CODE REVIEW

**Comment by AngeloStavrow** [comment]
Hey @metbril, thanks for opening this PR! Per the [Contributing guide](https://github.com/AngeloStavrow/indigo/blob/master/CONTRIBUTING.md), I opened #71 for you to discuss what your goal for this change is. Care to share your thoughts there?

**Comment by metbril** [comment]
Well the PR description says it all. 

> Make site logo configurable, just like in the h-card.

**Comment by AngeloStavrow** [comment]
> Well the PR description says it all.
> 
> > Make site logo configurable, just like in the h-card.

Fair enough. ¯\\_(ツ)\_/¯

Okay, so this PR will make the site logo (a static asset) identical to the profile picture that goes in the author bio (which gets set in **config.toml**). Certainly, I can imagine some people wanting their face as the site logo, but this doesn't feel like the best way to achieve your goal without breaking the theme for others.

The site logo is (currently) configurable by creating your own logo as an SVG, and replacing the Indigo logo in **/static/images/site-logo.svg**. This isn't documented anywhere, and that's my bad! It also forces an SVG on people, so that's potentially unpleasant.

For maximum flexibility, I'd instead recommend creating another entry in **config.toml** for e.g. `Site.Params.SiteLogo` and having **/layouts/partials/header.html** point to _that_.

Want to take a crack at that?

**Comment by AngeloStavrow** [comment]
Closing this stale PR. Feel free to re-open if you want to take a crack at the requested changes!

**Pull request closed without merging**
